[project]
name = "python-pig-latin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sockcrates", email = "17348049+sockcrates@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
python-pig-latin = "python_pig_latin:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.10",
    "ty>=0.0.85",
]

[tool.ruff]
target-version = "py313"
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["ALL"]

external = []
unfixable = ["ERA001"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = false
ignore-fully-untyped = false
suppress-none-returning = false

[tool.ruff.lint.flake8-type-checking]
strict = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
force-sort-within-sections = true
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true

[tool.ty.rules]
blanket-ignore-comment = "error"
dynamic-function-decorator-return = "error"
missing-type-argument = "error"
possibly-unresolved-reference = "error"
unsound-assignment = "error"
unsound-return-statement = "error"
unsound-yield = "error"
unsupported-dynamic-base = "error"

[tool.ty.analysis]
strict-equality-semantics = true
strict-generic-narrowing = true
